### ISSUE TITLE
karma.conf.js not found

### ISSUE THREAD

**Issue by martinoppitz** [Forumouth/gulp-karma-runner#5]
```js
  .pipe(karma.runner({
      configFile: './karma.conf.js'
    }))
```

**Comment by hiroaki-yamamoto** [comment]
Hi,

Does `karma.conf.js` exists in the same directory of `gulpfile`?

**Comment by martinoppitz** [comment]
yes.

Now, I use karma directly :smile:

**Comment by hiroaki-yamamoto** [comment]
Hey! Don't close the issue!

It smells like a bug.

**Comment by hiroaki-yamamoto** [comment]
Perhaps Karma doesn't care about relative path:
https://github.com/karma-runner/karma/blob/master/lib/config.js#L284

**Comment by martinoppitz** [comment]
I think this module is also deprecated as gulp-karma.

**Comment by hiroaki-yamamoto** [comment]
If you think so, grunt-sass and grunt-contrib-sass are duplicated package names, gulp-sass and gulp-ruby-sass are also duplicated package names. How about karma-sinon-chai, karma-sinon, and karma-chai? I'm not sure about my case, but that package provides karma server only while this package provides the both of runner and server. Moreover, gulp-karma that [official staff released](https://github.com/karma-runner/gulp-karma), is **JUST** and example of use.

**Comment by martinoppitz** [comment]
Both modules are deprecated. Use karma its self.

**Comment by martinoppitz** [comment]
In gulp-karma-runner there is the same warning also in gulp-karma. Use only karma.

**Comment by hiroaki-yamamoto** [comment]
I apologise my misunderstanding. Could you please create a new issue and post the warning? I will review it.

**Comment by martinoppitz** [comment]
Do not use `gulp.start` ...
